# Generated by Django 4.2 on 2025-08-21 05:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mk", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="是否为员工"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=False, verbose_name="是否为超级用户"),
        ),
    ]
