# Generated by Django 4.2 on 2025-08-21 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("mk", "0002_user_is_staff_alter_user_is_superuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="approval_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="审批时间"),
        ),
        migrations.AddField(
            model_name="user",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="审批人",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="rejection_reason",
            field=models.TextField(blank=True, verbose_name="拒绝原因"),
        ),
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[("pending", "审批中"), ("approved", "已通过"), ("rejected", "已拒绝")],
                default="pending",
                max_length=20,
                verbose_name="审批状态",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "超级管理员"),
                    ("department_manager", "部门管理员"),
                    ("store_operator", "店铺运营"),
                    ("staff", "普通员工"),
                ],
                default="staff",
                max_length=20,
                verbose_name="用户角色",
            ),
        ),
        migrations.CreateModel(
            name="AdminInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "invitee_email",
                    models.EmailField(max_length=254, verbose_name="被邀请人邮箱"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("super_admin", "超级管理员"),
                            ("department_manager", "部门管理员"),
                            ("store_operator", "店铺运营"),
                            ("staff", "普通员工"),
                        ],
                        max_length=20,
                        verbose_name="邀请角色",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="邀请令牌"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("accepted", "已接受"),
                            ("rejected", "已拒绝"),
                            ("expired", "已过期"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="邀请状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="过期时间")),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mk.department",
                        verbose_name="所属部门",
                    ),
                ),
                (
                    "inviter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="邀请人",
                    ),
                ),
            ],
            options={
                "verbose_name": "管理员邀请",
                "verbose_name_plural": "管理员邀请",
                "db_table": "admin_invitations",
            },
        ),
    ]
