# Generated by Django 4.2.7 on 2024-01-01 00:00:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mk', '0003_user_approval_date_user_approved_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, verbose_name='分类描述')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mk.productcategory', verbose_name='父分类')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '产品分类',
                'verbose_name_plural': '产品分类',
                'db_table': 'product_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200, verbose_name='产品名')),
                ('product_model', models.CharField(max_length=100, verbose_name='产品型号')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU编码')),
                ('inventory', models.IntegerField(default=0, verbose_name='库存')),
                ('unit_weight', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='单位重量(kg)')),
                ('min_stock', models.IntegerField(default=0, verbose_name='最低库存')),
                ('max_stock', models.IntegerField(default=1000, verbose_name='最高库存')),
                ('production_date', models.DateField(verbose_name='生产日期')),
                ('production_method', models.CharField(max_length=50, verbose_name='生产方式')),
                ('production_batch', models.CharField(max_length=50, verbose_name='生产批次')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='采购价格')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='销售售价')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单位成本')),
                ('sales_purpose', models.CharField(max_length=100, verbose_name='销售用途')),
                ('sales_date', models.DateField(blank=True, null=True, verbose_name='销售日期')),
                ('sales_profit_margin', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='销售利润率(%)')),
                ('sales_profit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='销售利润')),
                ('sales_gross_profit_margin', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='销售毛利率(%)')),
                ('sales_gross_profit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='销售毛利')),
                ('total_profit', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='总利润')),
                ('listing_time', models.DateTimeField(verbose_name='上架时间')),
                ('delisting_time', models.DateTimeField(blank=True, null=True, verbose_name='下架时间')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mk.productcategory', verbose_name='产品分类')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mk.user', verbose_name='创建人')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mk.store', verbose_name='所属店铺')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='products/', verbose_name='产品图片')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='图片描述')),
                ('is_primary', models.BooleanField(default=False, verbose_name='是否主图')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mk.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '产品图片',
                'verbose_name_plural': '产品图片',
                'db_table': 'product_images',
                'ordering': ['-is_primary', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('purchase', '采购入库'), ('sale', '销售出库'), ('return', '退货入库'), ('adjustment', '库存调整'), ('transfer', '店铺调拨')], max_length=20, verbose_name='交易类型')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='总金额')),
                ('reference_number', models.CharField(blank=True, max_length=50, verbose_name='参考单号')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mk.user', verbose_name='操作员')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mk.product', verbose_name='产品')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mk.store', verbose_name='店铺')),
            ],
            options={
                'verbose_name': '产品交易记录',
                'verbose_name_plural': '产品交易记录',
                'db_table': 'product_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store', 'product_name'], name='products_store_id_123456'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='products_sku_123456'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['production_date'], name='products_product_123456'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sales_date'], name='products_sales_da_123456'),
        ),
    ]
