# Generated by Django 4.2 on 2025-08-22 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mk.models.store_management
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("mk", "0004_product_management"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=100, verbose_name="SKU")),
                ("current_stock", models.IntegerField(default=0, verbose_name="当前库存")),
                ("reserved_stock", models.IntegerField(default=0, verbose_name="预留库存")),
                (
                    "available_stock",
                    models.IntegerField(default=0, verbose_name="可用库存"),
                ),
                ("min_stock", models.IntegerField(default=0, verbose_name="最小库存")),
                ("max_stock", models.IntegerField(default=0, verbose_name="最大库存")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否激活")),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="最后更新时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "库存",
                "verbose_name_plural": "库存",
                "db_table": "inventory",
                "ordering": ["store", "product", "sku"],
            },
        ),
        migrations.CreateModel(
            name="InventoryConsumption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=100, verbose_name="SKU")),
                (
                    "total_consumed",
                    models.IntegerField(default=0, verbose_name="总消耗数量"),
                ),
                ("total_orders", models.IntegerField(default=0, verbose_name="总订单数")),
                (
                    "last_consumption_date",
                    models.DateField(blank=True, null=True, verbose_name="最后消耗日期"),
                ),
                (
                    "first_consumption_date",
                    models.DateField(blank=True, null=True, verbose_name="首次消耗日期"),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="最后更新时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "库存消耗统计",
                "verbose_name_plural": "库存消耗统计",
                "db_table": "inventory_consumption",
                "ordering": ["store", "sku"],
            },
        ),
        migrations.CreateModel(
            name="InventoryTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("IN", "入库"),
                            ("OUT", "出库"),
                            ("RESERVE", "预留"),
                            ("RELEASE", "释放预留"),
                            ("ADJUST", "调整"),
                            ("DEDUCT_ORDER", "订单扣除"),
                        ],
                        max_length=20,
                        verbose_name="交易类型",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="数量")),
                ("before_stock", models.IntegerField(verbose_name="交易前库存")),
                ("after_stock", models.IntegerField(verbose_name="交易后库存")),
                ("notes", models.TextField(blank=True, null=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "库存交易记录",
                "verbose_name_plural": "库存交易记录",
                "db_table": "inventory_transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(max_length=100, unique=True, verbose_name="订单号"),
                ),
                ("country", models.CharField(max_length=50, verbose_name="国家")),
                ("store_code", models.CharField(max_length=50, verbose_name="店铺代号")),
                ("sku", models.CharField(max_length=100, verbose_name="SKU")),
                ("detail", models.TextField(verbose_name="Detail")),
                ("n_quantity", models.IntegerField(verbose_name="N数量")),
                ("c1_value", models.CharField(max_length=100, verbose_name="C1")),
                ("c2_value", models.CharField(max_length=100, verbose_name="C2")),
                ("order_date", models.DateField(verbose_name="出单日期")),
                ("label_status", models.CharField(max_length=50, verbose_name="标签状态")),
                (
                    "package_status",
                    models.CharField(max_length=50, verbose_name="包裹状态"),
                ),
                (
                    "combined_express_waybill",
                    models.CharField(max_length=100, verbose_name="寄合快递单号"),
                ),
                ("yuntu_info", models.CharField(max_length=100, verbose_name="云途")),
                ("last_mile", models.CharField(max_length=100, verbose_name="尾程")),
                ("store_name", models.CharField(max_length=200, verbose_name="店铺名称")),
                ("english_name", models.CharField(max_length=200, verbose_name="英文名")),
                ("first_sku", models.CharField(max_length=100, verbose_name="第一个sku")),
                (
                    "last_update_time",
                    models.DateTimeField(auto_now=True, verbose_name="最后更新时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "page_token",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="分页令牌"
                    ),
                ),
                (
                    "is_processed",
                    models.BooleanField(default=False, verbose_name="是否已处理"),
                ),
                (
                    "inventory_deducted",
                    models.BooleanField(default=False, verbose_name="库存是否已扣除"),
                ),
            ],
            options={
                "verbose_name": "订单",
                "verbose_name_plural": "订单",
                "db_table": "orders",
                "ordering": ["-order_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(max_length=100, unique=True, verbose_name="批次ID"),
                ),
                (
                    "execution_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="执行时间"),
                ),
                (
                    "page_token",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="分页令牌"
                    ),
                ),
                ("orders_count", models.IntegerField(default=0, verbose_name="订单数量")),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="是否完成"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
            ],
            options={
                "verbose_name": "订单批次",
                "verbose_name_plural": "订单批次",
                "db_table": "order_batches",
                "ordering": ["-execution_time"],
            },
        ),
        migrations.CreateModel(
            name="StoreInventory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("product_name", models.CharField(max_length=200, verbose_name="产品名称")),
                ("product_code", models.CharField(max_length=50, verbose_name="产品编码")),
                ("quantity", models.IntegerField(default=0, verbose_name="库存数量")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="单价"
                    ),
                ),
                ("min_stock", models.IntegerField(default=0, verbose_name="最低库存")),
                ("max_stock", models.IntegerField(default=1000, verbose_name="最高库存")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "店铺库存",
                "verbose_name_plural": "店铺库存",
                "db_table": "store_inventory",
            },
        ),
        migrations.CreateModel(
            name="StoreTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("sale", "销售"),
                            ("purchase", "采购"),
                            ("return", "退货"),
                            ("adjustment", "库存调整"),
                        ],
                        max_length=20,
                        verbose_name="交易类型",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="交易金额"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="交易描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "店铺交易记录",
                "verbose_name_plural": "店铺交易记录",
                "db_table": "store_transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="store",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "店铺",
                "verbose_name_plural": "店铺",
            },
        ),
        migrations.RenameField(
            model_name="product",
            old_name="inventory",
            new_name="stock_quantity",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="products_store_i_af7792_idx",
            old_name="products_store_id_123456",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="products_sku_fe2039_idx",
            old_name="products_sku_123456",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="products_product_39d081_idx",
            old_name="products_product_123456",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="products_sales_d_d6a16b_idx",
            old_name="products_sales_da_123456",
        ),
        migrations.AddField(
            model_name="store",
            name="business_hours",
            field=models.CharField(blank=True, max_length=100, verbose_name="营业时间"),
        ),
        migrations.AddField(
            model_name="store",
            name="code",
            field=models.CharField(
                default=mk.models.store_management.generate_store_code,
                max_length=20,
                unique=True,
                verbose_name="店铺编码",
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="description",
            field=models.TextField(blank=True, verbose_name="店铺描述"),
        ),
        migrations.AddField(
            model_name="store",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="店铺邮箱"),
        ),
        migrations.AddField(
            model_name="store",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_stores",
                to=settings.AUTH_USER_MODEL,
                verbose_name="店铺经理",
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "营业中"),
                    ("inactive", "暂停营业"),
                    ("closed", "已关闭"),
                    ("maintenance", "维护中"),
                ],
                default="active",
                max_length=20,
                verbose_name="店铺状态",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AlterField(
            model_name="producttransaction",
            name="operator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="操作员",
            ),
        ),
        migrations.AddField(
            model_name="storetransaction",
            name="operator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="操作员",
            ),
        ),
        migrations.AddField(
            model_name="storetransaction",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mk.store",
                verbose_name="所属店铺",
            ),
        ),
        migrations.AddField(
            model_name="storeinventory",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mk.store",
                verbose_name="所属店铺",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mk.store",
                verbose_name="店铺",
            ),
        ),
        migrations.AddField(
            model_name="inventorytransaction",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="操作人",
            ),
        ),
        migrations.AddField(
            model_name="inventorytransaction",
            name="inventory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mk.inventory",
                verbose_name="库存",
            ),
        ),
        migrations.AddField(
            model_name="inventorytransaction",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mk.order",
                verbose_name="关联订单",
            ),
        ),
        migrations.AddField(
            model_name="inventoryconsumption",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mk.store",
                verbose_name="店铺",
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_items",
                to="mk.product",
                verbose_name="产品",
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mk.store",
                verbose_name="店铺",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="storeinventory",
            unique_together={("store", "product_code")},
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["order_number"], name="orders_order_n_1336be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["store_code"], name="orders_store_c_89953c_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["sku"], name="orders_sku_534dfa_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["order_date"], name="orders_order_d_6e39a9_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["is_processed"], name="orders_is_proc_a37f74_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorytransaction",
            index=models.Index(
                fields=["inventory", "transaction_type"],
                name="inventory_t_invento_492a0d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="inventorytransaction",
            index=models.Index(
                fields=["created_at"], name="inventory_t_created_f087fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorytransaction",
            index=models.Index(fields=["order"], name="inventory_t_order_i_5381a2_idx"),
        ),
        migrations.AddIndex(
            model_name="inventoryconsumption",
            index=models.Index(
                fields=["store", "sku"], name="inventory_c_store_i_4762fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryconsumption",
            index=models.Index(
                fields=["total_consumed"], name="inventory_c_total_c_b2f6c0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="inventoryconsumption",
            unique_together={("store", "sku")},
        ),
        migrations.AddIndex(
            model_name="inventory",
            index=models.Index(
                fields=["store", "sku"], name="inventory_store_i_930ed7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventory",
            index=models.Index(
                fields=["current_stock"], name="inventory_current_0554c1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventory",
            index=models.Index(
                fields=["is_active"], name="inventory_is_acti_3b2601_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="inventory",
            unique_together={("store", "product", "sku")},
        ),
    ]
