# Generated by Django 4.2 on 2025-08-25 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("mk", "0005_inventory_inventoryconsumption_inventorytransaction_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="聊天室名称")),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("private", "私聊"),
                            ("group", "群聊"),
                            ("system", "系统消息"),
                        ],
                        default="group",
                        max_length=20,
                        verbose_name="聊天室类型",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否激活")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_rooms",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "聊天室",
                "verbose_name_plural": "聊天室",
                "db_table": "chat_rooms",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="InventoryWarning",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "warning_level",
                    models.CharField(
                        choices=[
                            ("low", "低库存"),
                            ("critical", "严重缺货"),
                            ("out_of_stock", "无库存"),
                        ],
                        max_length=20,
                        verbose_name="预警级别",
                    ),
                ),
                ("current_stock", models.IntegerField(verbose_name="当前库存")),
                ("threshold_stock", models.IntegerField(verbose_name="预警阈值")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "活跃"),
                            ("resolved", "已解决"),
                            ("ignored", "已忽略"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "email_sent",
                    models.BooleanField(default=False, verbose_name="邮件是否已发送"),
                ),
                (
                    "email_sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="邮件发送时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="解决时间"),
                ),
                (
                    "inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mk.inventory",
                        verbose_name="库存记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "库存预警",
                "verbose_name_plural": "库存预警",
                "db_table": "inventory_warnings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "文本"),
                            ("image", "图片"),
                            ("file", "文件"),
                            ("system", "系统消息"),
                            ("warning", "预警消息"),
                        ],
                        default="text",
                        max_length=20,
                        verbose_name="消息类型",
                    ),
                ),
                ("content", models.TextField(verbose_name="消息内容")),
                (
                    "file_url",
                    models.URLField(blank=True, null=True, verbose_name="文件链接"),
                ),
                (
                    "file_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="文件名"
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="文件大小(字节)"
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="是否已读")),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否已删除"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="发送时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "inventory_warning",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mk.inventorywarning",
                        verbose_name="关联库存预警",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mk.chatroom",
                        verbose_name="聊天室",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发送者",
                    ),
                ),
            ],
            options={
                "verbose_name": "消息",
                "verbose_name_plural": "消息",
                "db_table": "messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="WarningNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notified_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="通知时间"),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="是否已读")),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="阅读时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
                (
                    "warning",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mk.inventorywarning",
                        verbose_name="预警",
                    ),
                ),
            ],
            options={
                "verbose_name": "预警通知",
                "verbose_name_plural": "预警通知",
                "db_table": "warning_notifications",
                "unique_together": {("warning", "user")},
            },
        ),
        migrations.AddField(
            model_name="inventorywarning",
            name="notified_users",
            field=models.ManyToManyField(
                related_name="received_warnings",
                through="mk.WarningNotification",
                to=settings.AUTH_USER_MODEL,
                verbose_name="已通知用户",
            ),
        ),
        migrations.AddField(
            model_name="inventorywarning",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mk.product",
                verbose_name="产品",
            ),
        ),
        migrations.AddField(
            model_name="inventorywarning",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_warnings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="解决人",
            ),
        ),
        migrations.AddField(
            model_name="inventorywarning",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mk.store",
                verbose_name="店铺",
            ),
        ),
        migrations.CreateModel(
            name="ChatRoomMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "管理员"),
                            ("member", "普通成员"),
                            ("readonly", "只读成员"),
                        ],
                        default="member",
                        max_length=20,
                        verbose_name="角色",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="加入时间"),
                ),
                (
                    "last_read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后阅读时间"),
                ),
                ("is_muted", models.BooleanField(default=False, verbose_name="是否静音")),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mk.chatroom",
                        verbose_name="聊天室",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "聊天室成员",
                "verbose_name_plural": "聊天室成员",
                "db_table": "chat_room_members",
                "ordering": ["joined_at"],
            },
        ),
        migrations.AddField(
            model_name="chatroom",
            name="members",
            field=models.ManyToManyField(
                through="mk.ChatRoomMember",
                to=settings.AUTH_USER_MODEL,
                verbose_name="成员",
            ),
        ),
        migrations.CreateModel(
            name="MessageReadStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="阅读时间"),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mk.message",
                        verbose_name="消息",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "消息阅读状态",
                "verbose_name_plural": "消息阅读状态",
                "db_table": "message_read_status",
                "unique_together": {("message", "user")},
            },
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["room", "created_at"], name="messages_room_id_72ec70_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["sender", "created_at"], name="messages_sender__bf8b1c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["message_type"], name="messages_message_5af74b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorywarning",
            index=models.Index(
                fields=["store", "status"], name="inventory_w_store_i_0c7b96_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorywarning",
            index=models.Index(
                fields=["warning_level", "status"],
                name="inventory_w_warning_a2a969_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="inventorywarning",
            index=models.Index(
                fields=["created_at"], name="inventory_w_created_97ce12_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chatroommember",
            unique_together={("room", "user")},
        ),
    ]
